# Configuración para Rasa 3.1
recipe: default.v1
language: es  # ← Español

# ==========================================
# PIPELINE: Cómo procesar el lenguaje
# ==========================================
pipeline:
  # Tokenización: divide texto en palabras
- name: WhitespaceTokenizer

  # Expresiones regulares: detecta patrones
- name: RegexFeaturizer

  # Características léxicas y sintácticas
- name: LexicalSyntacticFeaturizer

  # Contador de palabras (unigramas y bigramas)
- name: CountVectorsFeaturizer

  # Contador de caracteres (para errores de escritura)
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4

  # Clasificador DIET: el cerebro que entiende intents
- name: DIETClassifier
  epochs: 100
  constrain_similarities: true

  # Mapeo de sinónimos
- name: EntitySynonymMapper

  # Selector de respuestas
- name: ResponseSelector
  epochs: 100

  # Fallback: cuando no está seguro
- name: FallbackClassifier
  threshold: 0.6    # Si confianza < 60%, activar fallback
  ambiguity_threshold: 0.1

# ==========================================
# POLICIES: Cómo decidir qué acción tomar
# ==========================================
policies:
  # Memoriza conversaciones exactas
- name: MemoizationPolicy

  # Aplica reglas (rules.yml)
- name: RulePolicy

  # Maneja intents inesperados
- name: UnexpecTEDIntentPolicy
  max_history: 5
  epochs: 100

  # Policy principal: aprende de stories
- name: TEDPolicy
  max_history: 5
  epochs: 100
  constrain_similarities: true
assistant_id: 20251012-112324-genteel-support
